test:
	python test_ldict.py
	python test_node.py
	python test_hashdb.py
	python test_hashdb_sqlite.py
	python test_dagger.py
	python test_iterator.py
	@echo SUCCESS. All tests passed.

clean:
	-rm -f ? tmp* *.tmp *.pyc .* *.sqlite *~
